package sjs.diffless

object attrs extends attrs

trait attrs {
	object accept
	object acceptCharset
	object accessKey
	object action
	object align
	object alt
	object altHtml
	object async
	object autocomplete
	object autofocus
	object autoplay
	object BaseHref
	object border
	object borderColor
	object borderColorDark
	object borderColorLight
	object charset
	object checked
	object citeAttr
	object classid
	object classList
	object className
	object cols
	object colSpan
	object content
	object contentEditable
	object controls
	object coords
	object currentTime
	object data
	object dateTime
	object defaultChecked
	object defaultPlaybackRate
	object defaultSelected
	object defaultValue
	object defer
	object dir
	object disabled
	object download
	object draggable
	object encoding
	object enctype
	object event
	object files
	object filters
	object formAttr
	object formAction
	object formEnctype
	object formMethod
	object formNoValidate
	object formTarget
	object gotpointercapture
	object hash
	object height
	object host
	object hostname
	object href
	object hreflang
	object htmlFor
	object httpEquiv
	object id
	object indeterminate
	object innerHTML
	object isMap
	object kind
	object labelAttr
	object list
	object loop
	object lostpointercapture
	object max
	object maxLength
	object media
	object method
	object mimeType
	object min
	object multiple
	object muted
	object name
	object naturalHeight
	object naturalWidth
	object noValidate
	object noWrap
	object objectAttr
	object onabort
	object onactivate
	object onafterprint
	object onbeforeactivate
	object onbeforecopy
	object onbeforecut
	object onbeforedeactivate
	object onbeforepaste
	object onbeforeprint
	object onbeforeunload
	object onblur
	object oncanplay
	object oncanplaythrough
	object onchange
	object onclick
	object oncontextmenu
	object oncopy
	object oncuechange
	object oncut
	object ondblclick
	object ondeactivate
	object ondrag
	object ondragend
	object ondragenter
	object ondragleave
	object ondragover
	object ondragstart
	object ondrop
	object ondurationchange
	object onemptied
	object onended
	object onerror
	object onfocus
	object onfocusin
	object onfocusout
	object onhashchange
	object onhelp
	object oninput
	object onkeydown
	object onkeypress
	object onkeyup
	object onload
	object onloadeddata
	object onloadedmetadata
	object onloadstart
	object onmessage
	object onmousedown
	object onmouseenter
	object onmouseleave
	object onmousemove
	object onmouseout
	object onmouseover
	object onmouseup
	object onmousewheel
	object onoffline
	object ononline
	object onpaste
	object onpause
	object onplay
	object onplaying
	object onpointercancel
	object onpointerdown
	object onpointerenter
	object onpointerleave
	object onpointermove
	object onpointerout
	object onpointerover
	object onpointerup
	object onpopstate
	object onprogress
	object onratechange
	object onreadystatechange
	object onreset
	object onresize
	object onscroll
	object onseeked
	object onseeking
	object onselect
	object onselectstart
	object onstalled
	object onstorage
	object onsubmit
	object onsuspend
	object ontimeupdate
	object onunload
	object onvolumechange
	object onwaiting
	object outerHTML
	object parentElement
	object pathname
	object pattern
	object placeholder
	object playbackRate
	object port
	object poster
	object preload
	object protocol
	object readOnly
	object readyState
	object recordNumber
	object rel
	object required
	object rev
	object rows
	object rowSpan
	object sandbox
	object scroll
	object scrollLeft
	object scrollTop
	object search
	object security
	object selected
	object selectedIndex
	object selectionEnd
	object selectionStart
	object shape
	object size
	object spanAttr
	object spellcheck
	object src
	object srclang
	object start
	object status
	object step
	object tabIndex
	object target
	object textAttr
	object titleAttr
	object `type`
	object url
	object useMap
	object value
	object valueAsNumber
	object volume
	object width
	object wrap
}
