package sjs.diffless

import scala.scalajs.js
import org.scalajs.dom.raw._

object setters extends setters

/** AttributeSetter instances for each tag/attribute combination possible */
trait setters extends attributes {
	implicit val Element_scrollTop						= AttributeSetter[scrollTop.type,			Element,				Double]								(_.scrollTop	= _)
	implicit val Element_scrollLeft						= AttributeSetter[scrollLeft.type,			Element,				Double]								(_.scrollLeft	= _)
	implicit val Element_outerHTML						= AttributeSetter[outerHTML.type,			Element,				String]								(_.outerHTML	= _)
	implicit val Element_innerHTML						= AttributeSetter[innerHTML.type,			Element,				String]								(_.innerHTML	= _)
	implicit val Element_id								= AttributeSetter[id.type,					Element,				String]								(_.id	= _)
	implicit val Element_oncopy							= AttributeSetter[oncopy.type,				Element,				js.Function1[ClipboardEvent, _]]	(_.oncopy	= _)
	implicit val Element_oncut							= AttributeSetter[oncut.type,				Element,				js.Function1[ClipboardEvent, _]]	(_.oncut	= _)
	implicit val Element_onpaste						= AttributeSetter[onpaste.type,				Element,				js.Function1[ClipboardEvent, _]]	(_.onpaste	= _)
	implicit val Element_accessKey						= AttributeSetter[accessKey.type,			Element,				String]								(_.accessKey	= _)
	implicit val Element_classList						= AttributeSetter[classList.type,			Element,				DOMTokenList]						(_.classList	= _)

	implicit val HTMLBaseElement_target					= AttributeSetter[target.type,				HTMLBaseElement,		String]								(_.target	= _)
	implicit val HTMLBaseElement_href					= AttributeSetter[href.type,				HTMLBaseElement,		String]								(_.href	= _)

	implicit val HTMLOListElement_start					= AttributeSetter[start.type,				HTMLOListElement,		Int]								(_.start	= _)

	implicit val HTMLSelectElement_value				= AttributeSetter[value.type,				HTMLSelectElement,		String]								(_.value	= _)
	implicit val HTMLSelectElement_name					= AttributeSetter[name.type,				HTMLSelectElement,		String]								(_.name	= _)
	implicit val HTMLSelectElement_size					= AttributeSetter[size.type,				HTMLSelectElement,		Int]								(_.size	= _)
	implicit val HTMLSelectElement_selectedIndex		= AttributeSetter[selectedIndex.type,		HTMLSelectElement,		Int]								(_.selectedIndex	= _)
	implicit val HTMLSelectElement_multiple				= AttributeSetter[multiple.type,			HTMLSelectElement,		Boolean]							(_.multiple	= _)
	implicit val HTMLSelectElement_disabled				= AttributeSetter[disabled.type,			HTMLSelectElement,		Boolean]							(_.disabled	= _)
	implicit val HTMLSelectElement_autofocus			= AttributeSetter[autofocus.type,			HTMLSelectElement,		Boolean]							(_.autofocus	= _)
	implicit val HTMLSelectElement_required				= AttributeSetter[required.type,			HTMLSelectElement,		Boolean]							(_.required	= _)

	implicit val HTMLBlockElement_width					= AttributeSetter[width.type,				HTMLBlockElement,		Double]								(_.width	= _)
	implicit val HTMLBlockElement_cite					= AttributeSetter[citeAttr.type,			HTMLBlockElement,		String]								(_.cite	= _)

	implicit val HTMLMetaElement_httpEquiv				= AttributeSetter[httpEquiv.type,			HTMLMetaElement,		String]								(_.httpEquiv	= _)
	implicit val HTMLMetaElement_name					= AttributeSetter[name.type,				HTMLMetaElement,		String]								(_.name	= _)
	implicit val HTMLMetaElement_content				= AttributeSetter[content.type,				HTMLMetaElement,		String]								(_.content	= _)
	implicit val HTMLMetaElement_url					= AttributeSetter[url.type,					HTMLMetaElement,		String]								(_.url	= _)
	implicit val HTMLMetaElement_charset				= AttributeSetter[charset.type,				HTMLMetaElement,		String]								(_.charset	= _)

	implicit val HTMLDDElement_noWrap					= AttributeSetter[noWrap.type,				HTMLDDElement,			Boolean]							(_.noWrap	= _)

	implicit val HTMLLinkElement_rel					= AttributeSetter[rel.type,					HTMLLinkElement,		String]								(_.rel	= _)
	implicit val HTMLLinkElement_target					= AttributeSetter[target.type,				HTMLLinkElement,		String]								(_.target	= _)
	implicit val HTMLLinkElement_href					= AttributeSetter[href.type,				HTMLLinkElement,		String]								(_.href	= _)
	implicit val HTMLLinkElement_media					= AttributeSetter[media.type,				HTMLLinkElement,		String]								(_.media	= _)
	implicit val HTMLLinkElement_rev					= AttributeSetter[rev.type,					HTMLLinkElement,		String]								(_.rev	= _)
	implicit val HTMLLinkElement_type					= AttributeSetter[`type`.type,				HTMLLinkElement,		String]								(_.`type`	= _)
	implicit val HTMLLinkElement_hreflang				= AttributeSetter[hreflang.type,			HTMLLinkElement,		String]								(_.hreflang	= _)

	implicit val HTMLOptionElement_defaultSelected		= AttributeSetter[defaultSelected.type,		HTMLOptionElement,		Boolean]							(_.defaultSelected	= _)
	implicit val HTMLOptionElement_value				= AttributeSetter[value.type,				HTMLOptionElement,		String]								(_.value	= _)
	implicit val HTMLOptionElement_text					= AttributeSetter[textAttr.type,			HTMLOptionElement,		String]								(_.text	= _)
	implicit val HTMLOptionElement_label				= AttributeSetter[labelAttr.type,			HTMLOptionElement,		String]								(_.label	= _)
	implicit val HTMLOptionElement_selected				= AttributeSetter[selected.type,			HTMLOptionElement,		Boolean]							(_.selected	= _)
	implicit val HTMLOptionElement_disabled				= AttributeSetter[disabled.type,			HTMLOptionElement,		Boolean]							(_.disabled	= _)

	implicit val HTMLMapElement_name					= AttributeSetter[name.type,				HTMLMapElement,			String]								(_.name	= _)

	implicit val HTMLMenuElement_type					= AttributeSetter[`type`.type,				HTMLMenuElement,		String]								(_.`type`	= _)

	implicit val HTMLImageElement_width					= AttributeSetter[width.type,				HTMLImageElement,		Int]								(_.width	= _)
	implicit val HTMLImageElement_naturalHeight			= AttributeSetter[naturalHeight.type,		HTMLImageElement,		Int]								(_.naturalHeight	= _)
	implicit val HTMLImageElement_alt					= AttributeSetter[alt.type,					HTMLImageElement,		String]								(_.alt	= _)
	implicit val HTMLImageElement_src					= AttributeSetter[src.type,					HTMLImageElement,		String]								(_.src	= _)
	implicit val HTMLImageElement_useMap				= AttributeSetter[useMap.type,				HTMLImageElement,		String]								(_.useMap	= _)
	implicit val HTMLImageElement_naturalWidth			= AttributeSetter[naturalWidth.type,		HTMLImageElement,		Int]								(_.naturalWidth	= _)
	implicit val HTMLImageElement_height				= AttributeSetter[height.type,				HTMLImageElement,		Int]								(_.height	= _)
	implicit val HTMLImageElement_href					= AttributeSetter[href.type,				HTMLImageElement,		String]								(_.href	= _)
	implicit val HTMLImageElement_isMap					= AttributeSetter[isMap.type,				HTMLImageElement,		Boolean]							(_.isMap	= _)
	implicit val HTMLImageElement_onload				= AttributeSetter[onload.type,				HTMLImageElement,		js.Function1[Event, _]]				(_.onload	= _)

	implicit val HTMLAreaElement_protocol				= AttributeSetter[protocol.type,			HTMLAreaElement,		String]								(_.protocol	= _)
	implicit val HTMLAreaElement_search					= AttributeSetter[search.type,				HTMLAreaElement,		String]								(_.search	= _)
	implicit val HTMLAreaElement_alt					= AttributeSetter[alt.type,					HTMLAreaElement,		String]								(_.alt	= _)
	implicit val HTMLAreaElement_coords					= AttributeSetter[coords.type,				HTMLAreaElement,		String]								(_.coords	= _)
	implicit val HTMLAreaElement_hostname				= AttributeSetter[hostname.type,			HTMLAreaElement,		String]								(_.hostname	= _)
	implicit val HTMLAreaElement_port					= AttributeSetter[port.type,				HTMLAreaElement,		String]								(_.port	= _)
	implicit val HTMLAreaElement_pathname				= AttributeSetter[pathname.type,			HTMLAreaElement,		String]								(_.pathname	= _)
	implicit val HTMLAreaElement_host					= AttributeSetter[host.type,				HTMLAreaElement,		String]								(_.host	= _)
	implicit val HTMLAreaElement_hash					= AttributeSetter[hash.type,				HTMLAreaElement,		String]								(_.hash	= _)
	implicit val HTMLAreaElement_target					= AttributeSetter[target.type,				HTMLAreaElement,		String]								(_.target	= _)
	implicit val HTMLAreaElement_href					= AttributeSetter[href.type,				HTMLAreaElement,		String]								(_.href	= _)
	implicit val HTMLAreaElement_shape					= AttributeSetter[shape.type,				HTMLAreaElement,		String]								(_.shape	= _)

	implicit val HTMLButtonElement_value				= AttributeSetter[value.type,				HTMLButtonElement,		String]								(_.value	= _)
	implicit val HTMLButtonElement_status				= AttributeSetter[status.type,				HTMLButtonElement,		js.Any]								(_.status	= _)
	implicit val HTMLButtonElement_name					= AttributeSetter[name.type,				HTMLButtonElement,		String]								(_.name	= _)
	implicit val HTMLButtonElement_type					= AttributeSetter[`type`.type,				HTMLButtonElement,		String]								(_.`type`	= _)
	implicit val HTMLButtonElement_disabled				= AttributeSetter[disabled.type,			HTMLButtonElement,		Boolean]							(_.disabled	= _)
	implicit val HTMLButtonElement_formTarget			= AttributeSetter[formTarget.type,			HTMLButtonElement,		String]								(_.formTarget	= _)
	implicit val HTMLButtonElement_formAction			= AttributeSetter[formAction.type,			HTMLButtonElement,		String]								(_.formAction	= _)
	implicit val HTMLButtonElement_autofocus			= AttributeSetter[autofocus.type,			HTMLButtonElement,		Boolean]							(_.autofocus	= _)
	implicit val HTMLButtonElement_formNoValidate		= AttributeSetter[formNoValidate.type,		HTMLButtonElement,		String]								(_.formNoValidate	= _)
	implicit val HTMLButtonElement_formEnctype			= AttributeSetter[formEnctype.type,			HTMLButtonElement,		String]								(_.formEnctype	= _)
	implicit val HTMLButtonElement_formMethod			= AttributeSetter[formMethod.type,			HTMLButtonElement,		String]								(_.formMethod	= _)

	implicit val HTMLSourceElement_src					= AttributeSetter[src.type,					HTMLSourceElement,		String]								(_.src	= _)
	implicit val HTMLSourceElement_media				= AttributeSetter[media.type,				HTMLSourceElement,		String]								(_.media	= _)
	implicit val HTMLSourceElement_type					= AttributeSetter[`type`.type,				HTMLSourceElement,		String]								(_.`type`	= _)

	implicit val HTMLScriptElement_defer				= AttributeSetter[defer.type,				HTMLScriptElement,		Boolean]							(_.defer	= _)
	implicit val HTMLScriptElement_text					= AttributeSetter[textAttr.type,			HTMLScriptElement,		String]								(_.text	= _)
	implicit val HTMLScriptElement_src					= AttributeSetter[src.type,					HTMLScriptElement,		String]								(_.src	= _)
	implicit val HTMLScriptElement_charset				= AttributeSetter[charset.type,				HTMLScriptElement,		String]								(_.charset	= _)
	implicit val HTMLScriptElement_type					= AttributeSetter[`type`.type,				HTMLScriptElement,		String]								(_.`type`	= _)
	implicit val HTMLScriptElement_event				= AttributeSetter[event.type,				HTMLScriptElement,		String]								(_.event	= _)
	implicit val HTMLScriptElement_async				= AttributeSetter[async.type,				HTMLScriptElement,		Boolean]							(_.async	= _)
	implicit val HTMLScriptElement_onload				= AttributeSetter[onload.type,				HTMLScriptElement,		js.Function1[Event, _]]				(_.onload	= _)

	implicit val HTMLTableRowElement_borderColorLight	= AttributeSetter[borderColorLight.type,	HTMLTableRowElement,	js.Any]								(_.borderColorLight	= _)
	implicit val HTMLTableRowElement_borderColor		= AttributeSetter[borderColor.type,			HTMLTableRowElement,	js.Any]								(_.borderColor	= _)
	implicit val HTMLTableRowElement_height				= AttributeSetter[height.type,				HTMLTableRowElement,	js.Any]								(_.height	= _)
	implicit val HTMLTableRowElement_borderColorDark	= AttributeSetter[borderColorDark.type,		HTMLTableRowElement,	js.Any]								(_.borderColorDark	= _)

	implicit val HTMLQuoteElement_dateTime				= AttributeSetter[dateTime.type,			HTMLQuoteElement,		String]								(_.dateTime	= _)
	implicit val HTMLQuoteElement_cite					= AttributeSetter[citeAttr.type,			HTMLQuoteElement,		String]								(_.cite	= _)

	implicit val HTMLLabelElement_htmlFor				= AttributeSetter[htmlFor.type,				HTMLLabelElement,		String]								(_.htmlFor	= _)

	implicit val HTMLLegendElement_align				= AttributeSetter[align.type,				HTMLLegendElement,		String]								(_.align	= _)

	implicit val HTMLLIElement_value					= AttributeSetter[value.type,				HTMLLIElement,			Int]								(_.value	= _)

	implicit val HTMLIFrameElement_width				= AttributeSetter[width.type,				HTMLIFrameElement,		String]								(_.width	= _)
	implicit val HTMLIFrameElement_src					= AttributeSetter[src.type,					HTMLIFrameElement,		String]								(_.src	= _)
	implicit val HTMLIFrameElement_name					= AttributeSetter[name.type,				HTMLIFrameElement,		String]								(_.name	= _)
	implicit val HTMLIFrameElement_height				= AttributeSetter[height.type,				HTMLIFrameElement,		String]								(_.height	= _)
	implicit val HTMLIFrameElement_border				= AttributeSetter[border.type,				HTMLIFrameElement,		String]								(_.border	= _)
	implicit val HTMLIFrameElement_security				= AttributeSetter[security.type,			HTMLIFrameElement,		js.Any]								(_.security	= _)
	implicit val HTMLIFrameElement_onload				= AttributeSetter[onload.type,				HTMLIFrameElement,		js.Function1[Event, _]]				(_.onload	= _)
	implicit val HTMLIFrameElement_sandbox				= AttributeSetter[sandbox.type,				HTMLIFrameElement,		DOMSettableTokenList]				(_.sandbox	= _)

	implicit val HTMLBodyElement_scroll					= AttributeSetter[scroll.type,				HTMLBodyElement,		String]								(_.scroll	= _)
	implicit val HTMLBodyElement_ononline				= AttributeSetter[ononline.type,			HTMLBodyElement,		js.Function1[Event, _]]				(_.ononline	= _)
	implicit val HTMLBodyElement_onmessage				= AttributeSetter[onmessage.type,			HTMLBodyElement,		js.Function1[MessageEvent, _]]		(_.onmessage	= _)
	implicit val HTMLBodyElement_onerror				= AttributeSetter[onerror.type,				HTMLBodyElement,		js.Function1[Event, _]]				(_.onerror	= _)
	implicit val HTMLBodyElement_onresize				= AttributeSetter[onresize.type,			HTMLBodyElement,		js.Function1[UIEvent, _]]			(_.onresize	= _)
	implicit val HTMLBodyElement_onafterprint			= AttributeSetter[onafterprint.type,		HTMLBodyElement,		js.Function1[Event, _]]				(_.onafterprint	= _)
	implicit val HTMLBodyElement_onbeforeprint			= AttributeSetter[onbeforeprint.type,		HTMLBodyElement,		js.Function1[Event, _]]				(_.onbeforeprint	= _)
	implicit val HTMLBodyElement_onoffline				= AttributeSetter[onoffline.type,			HTMLBodyElement,		js.Function1[Event, _]]				(_.onoffline	= _)
	implicit val HTMLBodyElement_onunload				= AttributeSetter[onunload.type,			HTMLBodyElement,		js.Function1[Event, _]]				(_.onunload	= _)
	implicit val HTMLBodyElement_onhashchange			= AttributeSetter[onhashchange.type,		HTMLBodyElement,		js.Function1[Event, _]]				(_.onhashchange	= _)
	implicit val HTMLBodyElement_onload					= AttributeSetter[onload.type,				HTMLBodyElement,		js.Function1[Event, _]]				(_.onload	= _)
	implicit val HTMLBodyElement_onbeforeunload			= AttributeSetter[onbeforeunload.type,		HTMLBodyElement,		js.Function1[BeforeUnloadEvent, _]]	(_.onbeforeunload	= _)
	implicit val HTMLBodyElement_onstorage				= AttributeSetter[onstorage.type,			HTMLBodyElement,		js.Function1[StorageEvent, _]]		(_.onstorage	= _)
	implicit val HTMLBodyElement_onpopstate				= AttributeSetter[onpopstate.type,			HTMLBodyElement,		js.Function1[PopStateEvent, _]]		(_.onpopstate	= _)

	implicit val HTMLInputElement_width					= AttributeSetter[width.type,				HTMLInputElement,		String]								(_.width	= _)
	implicit val HTMLInputElement_status				= AttributeSetter[status.type,				HTMLInputElement,		Boolean]							(_.status	= _)
	implicit val HTMLInputElement_selectionStart		= AttributeSetter[selectionStart.type,		HTMLInputElement,		Int]								(_.selectionStart	= _)
	implicit val HTMLInputElement_indeterminate			= AttributeSetter[indeterminate.type,		HTMLInputElement,		Boolean]							(_.indeterminate	= _)
	implicit val HTMLInputElement_readOnly				= AttributeSetter[readOnly.type,			HTMLInputElement,		Boolean]							(_.readOnly	= _)
	implicit val HTMLInputElement_size					= AttributeSetter[size.type,				HTMLInputElement,		Int]								(_.size	= _)
	implicit val HTMLInputElement_selectionEnd			= AttributeSetter[selectionEnd.type,		HTMLInputElement,		Int]								(_.selectionEnd	= _)
	implicit val HTMLInputElement_accept				= AttributeSetter[accept.type,				HTMLInputElement,		String]								(_.accept	= _)
	implicit val HTMLInputElement_alt					= AttributeSetter[alt.type,					HTMLInputElement,		String]								(_.alt	= _)
	implicit val HTMLInputElement_defaultChecked		= AttributeSetter[defaultChecked.type,		HTMLInputElement,		Boolean]							(_.defaultChecked	= _)
	implicit val HTMLInputElement_value					= AttributeSetter[value.type,				HTMLInputElement,		String]								(_.value	= _)
	implicit val HTMLInputElement_src					= AttributeSetter[src.type,					HTMLInputElement,		String]								(_.src	= _)
	implicit val HTMLInputElement_name					= AttributeSetter[name.type,				HTMLInputElement,		String]								(_.name	= _)
	implicit val HTMLInputElement_height				= AttributeSetter[height.type,				HTMLInputElement,		String]								(_.height	= _)
	implicit val HTMLInputElement_checked				= AttributeSetter[checked.type,				HTMLInputElement,		Boolean]							(_.checked	= _)
	implicit val HTMLInputElement_disabled				= AttributeSetter[disabled.type,			HTMLInputElement,		Boolean]							(_.disabled	= _)
	implicit val HTMLInputElement_maxLength				= AttributeSetter[maxLength.type,			HTMLInputElement,		Int]								(_.maxLength	= _)
	implicit val HTMLInputElement_type					= AttributeSetter[`type`.type,				HTMLInputElement,		String]								(_.`type`	= _)
	implicit val HTMLInputElement_defaultValue			= AttributeSetter[defaultValue.type,		HTMLInputElement,		String]								(_.defaultValue	= _)
	implicit val HTMLInputElement_files					= AttributeSetter[files.type,				HTMLInputElement,		FileList]							(_.files	= _)
	implicit val HTMLInputElement_max					= AttributeSetter[max.type,					HTMLInputElement,		String]								(_.max	= _)
	implicit val HTMLInputElement_formTarget			= AttributeSetter[formTarget.type,			HTMLInputElement,		String]								(_.formTarget	= _)
	implicit val HTMLInputElement_step					= AttributeSetter[step.type,				HTMLInputElement,		String]								(_.step	= _)
	implicit val HTMLInputElement_autofocus				= AttributeSetter[autofocus.type,			HTMLInputElement,		Boolean]							(_.autofocus	= _)
	implicit val HTMLInputElement_required				= AttributeSetter[required.type,			HTMLInputElement,		Boolean]							(_.required	= _)
	implicit val HTMLInputElement_formEnctype			= AttributeSetter[formEnctype.type,			HTMLInputElement,		String]								(_.formEnctype	= _)
	implicit val HTMLInputElement_valueAsNumber			= AttributeSetter[valueAsNumber.type,		HTMLInputElement,		Double]								(_.valueAsNumber	= _)
	implicit val HTMLInputElement_placeholder			= AttributeSetter[placeholder.type,			HTMLInputElement,		String]								(_.placeholder	= _)
	implicit val HTMLInputElement_formMethod			= AttributeSetter[formMethod.type,			HTMLInputElement,		String]								(_.formMethod	= _)
	implicit val HTMLInputElement_list					= AttributeSetter[list.type,				HTMLInputElement,		HTMLElement]						(_.list	= _)
	implicit val HTMLInputElement_autocomplete			= AttributeSetter[autocomplete.type,		HTMLInputElement,		String]								(_.autocomplete	= _)
	implicit val HTMLInputElement_min					= AttributeSetter[min.type,					HTMLInputElement,		String]								(_.min	= _)
	implicit val HTMLInputElement_formAction			= AttributeSetter[formAction.type,			HTMLInputElement,		String]								(_.formAction	= _)
	implicit val HTMLInputElement_pattern				= AttributeSetter[pattern.type,				HTMLInputElement,		String]								(_.pattern	= _)
	implicit val HTMLInputElement_formNoValidate		= AttributeSetter[formNoValidate.type,		HTMLInputElement,		String]								(_.formNoValidate	= _)
	implicit val HTMLInputElement_multiple				= AttributeSetter[multiple.type,			HTMLInputElement,		Boolean]							(_.multiple	= _)

	implicit val HTMLAnchorElement_rel					= AttributeSetter[rel.type,					HTMLAnchorElement,		String]								(_.rel	= _)
	implicit val HTMLAnchorElement_protocol				= AttributeSetter[protocol.type,			HTMLAnchorElement,		String]								(_.protocol	= _)
	implicit val HTMLAnchorElement_search				= AttributeSetter[search.type,				HTMLAnchorElement,		String]								(_.search	= _)
	implicit val HTMLAnchorElement_hostname				= AttributeSetter[hostname.type,			HTMLAnchorElement,		String]								(_.hostname	= _)
	implicit val HTMLAnchorElement_pathname				= AttributeSetter[pathname.type,			HTMLAnchorElement,		String]								(_.pathname	= _)
	implicit val HTMLAnchorElement_target				= AttributeSetter[target.type,				HTMLAnchorElement,		String]								(_.target	= _)
	implicit val HTMLAnchorElement_href					= AttributeSetter[href.type,				HTMLAnchorElement,		String]								(_.href	= _)
	implicit val HTMLAnchorElement_charset				= AttributeSetter[charset.type,				HTMLAnchorElement,		String]								(_.charset	= _)
	implicit val HTMLAnchorElement_hreflang				= AttributeSetter[hreflang.type,			HTMLAnchorElement,		String]								(_.hreflang	= _)
	implicit val HTMLAnchorElement_port					= AttributeSetter[port.type,				HTMLAnchorElement,		String]								(_.port	= _)
	implicit val HTMLAnchorElement_host					= AttributeSetter[host.type,				HTMLAnchorElement,		String]								(_.host	= _)
	implicit val HTMLAnchorElement_hash					= AttributeSetter[hash.type,				HTMLAnchorElement,		String]								(_.hash	= _)
	implicit val HTMLAnchorElement_type					= AttributeSetter[`type`.type,				HTMLAnchorElement,		String]								(_.`type`	= _)
	implicit val HTMLAnchorElement_mimeType				= AttributeSetter[mimeType.type,			HTMLAnchorElement,		String]								(_.mimeType	= _)
	implicit val HTMLAnchorElement_text					= AttributeSetter[textAttr.type,			HTMLAnchorElement,		String]								(_.text	= _)
	// TODO hack: as download is experimental, it's not in the API as a property yet
	implicit val HTMLAnchorElement_download				= AttributeSetter[download.type,			HTMLAnchorElement,		String]								(_ setAttribute ("download", _))


	implicit val HTMLParamElement_value					= AttributeSetter[value.type,				HTMLParamElement,		String]								(_.value	= _)
	implicit val HTMLParamElement_name					= AttributeSetter[name.type,				HTMLParamElement,		String]								(_.name	= _)

	implicit val HTMLPhraseElement_dateTime				= AttributeSetter[dateTime.type,			HTMLPhraseElement,		String]								(_.dateTime	= _)

	implicit val HTMLCanvasElement_width				= AttributeSetter[width.type,				HTMLCanvasElement,		Int]								(_.width	= _)
	implicit val HTMLCanvasElement_height				= AttributeSetter[height.type,				HTMLCanvasElement,		Int]								(_.height	= _)

	implicit val HTMLTitleElement_text					= AttributeSetter[textAttr.type,			HTMLTitleElement,		String]								(_.text	= _)

	implicit val HTMLStyleElement_media					= AttributeSetter[media.type,				HTMLStyleElement,		String]								(_.media	= _)
	implicit val HTMLStyleElement_type					= AttributeSetter[`type`.type,				HTMLStyleElement,		String]								(_.`type`	= _)

	implicit val HTMLTableCellElement_colSpan			= AttributeSetter[colSpan.type,				HTMLTableCellElement,	Int]								(_.colSpan	= _)
	implicit val HTMLTableCellElement_rowSpan			= AttributeSetter[rowSpan.type,				HTMLTableCellElement,	Int]								(_.rowSpan	= _)

	implicit val HTMLTextAreaElement_value				= AttributeSetter[value.type,				HTMLTextAreaElement,	String]								(_.value	= _)
	implicit val HTMLTextAreaElement_status				= AttributeSetter[status.type,				HTMLTextAreaElement,	js.Any]								(_.status	= _)
	implicit val HTMLTextAreaElement_name				= AttributeSetter[name.type,				HTMLTextAreaElement,	String]								(_.name	= _)
	implicit val HTMLTextAreaElement_disabled			= AttributeSetter[disabled.type,			HTMLTextAreaElement,	Boolean]							(_.disabled	= _)
	implicit val HTMLTextAreaElement_selectionStart		= AttributeSetter[selectionStart.type,		HTMLTextAreaElement,	Int]								(_.selectionStart	= _)
	implicit val HTMLTextAreaElement_rows				= AttributeSetter[rows.type,				HTMLTextAreaElement,	Int]								(_.rows	= _)
	implicit val HTMLTextAreaElement_cols				= AttributeSetter[cols.type,				HTMLTextAreaElement,	Int]								(_.cols	= _)
	implicit val HTMLTextAreaElement_readOnly			= AttributeSetter[readOnly.type,			HTMLTextAreaElement,	Boolean]							(_.readOnly	= _)
	implicit val HTMLTextAreaElement_wrap				= AttributeSetter[wrap.type,				HTMLTextAreaElement,	String]								(_.wrap	= _)
	implicit val HTMLTextAreaElement_selectionEnd		= AttributeSetter[selectionEnd.type,		HTMLTextAreaElement,	Int]								(_.selectionEnd	= _)
	implicit val HTMLTextAreaElement_defaultValue		= AttributeSetter[defaultValue.type,		HTMLTextAreaElement,	String]								(_.defaultValue	= _)
	implicit val HTMLTextAreaElement_autofocus			= AttributeSetter[autofocus.type,			HTMLTextAreaElement,	Boolean]							(_.autofocus	= _)
	implicit val HTMLTextAreaElement_required			= AttributeSetter[required.type,			HTMLTextAreaElement,	Boolean]							(_.required	= _)
	implicit val HTMLTextAreaElement_maxLength			= AttributeSetter[maxLength.type,			HTMLTextAreaElement,	Int]								(_.maxLength	= _)
	implicit val HTMLTextAreaElement_placeholder		= AttributeSetter[placeholder.type,			HTMLTextAreaElement,	String]								(_.placeholder	= _)

	implicit val HTMLModElement_dateTime				= AttributeSetter[dateTime.type,			HTMLModElement,			String]								(_.dateTime	= _)
	implicit val HTMLModElement_cite					= AttributeSetter[citeAttr.type,			HTMLModElement,			String]								(_.cite	= _)

	implicit val HTMLTableColElement_span				= AttributeSetter[spanAttr.type,			HTMLTableColElement,	Int]								(_.span	= _)

	implicit val HTMLMediaElement_loop					= AttributeSetter[loop.type,				HTMLMediaElement,		Boolean]							(_.loop	= _)
	implicit val HTMLMediaElement_autoplay				= AttributeSetter[autoplay.type,			HTMLMediaElement,		Boolean]							(_.autoplay	= _)
	implicit val HTMLMediaElement_controls				= AttributeSetter[controls.type,			HTMLMediaElement,		Boolean]							(_.controls	= _)
	implicit val HTMLMediaElement_volume				= AttributeSetter[volume.type,				HTMLMediaElement,		Double]								(_.volume	= _)
	implicit val HTMLMediaElement_src					= AttributeSetter[src.type,					HTMLMediaElement,		String]								(_.src	= _)
	implicit val HTMLMediaElement_playbackRate			= AttributeSetter[playbackRate.type,		HTMLMediaElement,		Double]								(_.playbackRate	= _)
	implicit val HTMLMediaElement_muted					= AttributeSetter[muted.type,				HTMLMediaElement,		Boolean]							(_.muted	= _)
	implicit val HTMLMediaElement_defaultPlaybackRate	= AttributeSetter[defaultPlaybackRate.type,	HTMLMediaElement,		Double]								(_.defaultPlaybackRate	= _)
	implicit val HTMLMediaElement_currentTime			= AttributeSetter[currentTime.type,			HTMLMediaElement,		Double]								(_.currentTime	= _)
	implicit val HTMLMediaElement_preload				= AttributeSetter[preload.type,				HTMLMediaElement,		String]								(_.preload	= _)

	implicit val HTMLDTElement_noWrap					= AttributeSetter[noWrap.type,				HTMLDTElement,			Boolean]							(_.noWrap	= _)

	implicit val HTMLFieldSetElement_disabled			= AttributeSetter[disabled.type,			HTMLFieldSetElement,	Boolean]							(_.disabled	= _)

	implicit val HTMLElement_onblur						= AttributeSetter[onblur.type,				HTMLElement,			js.Function1[FocusEvent, _]]		(_.onblur	= _)
	implicit val HTMLElement_onfocus					= AttributeSetter[onfocus.type,				HTMLElement,			js.Function1[FocusEvent, _]]		(_.onfocus	= _)
	implicit val HTMLElement_onmouseleave				= AttributeSetter[onmouseleave.type,		HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseleave	= _)
	implicit val HTMLElement_onbeforecut				= AttributeSetter[onbeforecut.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.onbeforecut	= _)
	implicit val HTMLElement_onkeydown					= AttributeSetter[onkeydown.type,			HTMLElement,			js.Function1[KeyboardEvent, _]]		(_.onkeydown	= _)
	implicit val HTMLElement_onkeyup					= AttributeSetter[onkeyup.type,				HTMLElement,			js.Function1[KeyboardEvent, _]]		(_.onkeyup	= _)
	implicit val HTMLElement_onreset					= AttributeSetter[onreset.type,				HTMLElement,			js.Function1[Event, _]]				(_.onreset	= _)
	implicit val HTMLElement_onhelp						= AttributeSetter[onhelp.type,				HTMLElement,			js.Function1[Event, _]]				(_.onhelp	= _)
	implicit val HTMLElement_ondragleave				= AttributeSetter[ondragleave.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragleave	= _)
	implicit val HTMLElement_className					= AttributeSetter[className.type,			HTMLElement,			String]								(_.className	= _)
	implicit val HTMLElement_onfocusin					= AttributeSetter[onfocusin.type,			HTMLElement,			js.Function1[FocusEvent, _]]		(_.onfocusin	= _)
	implicit val HTMLElement_onseeked					= AttributeSetter[onseeked.type,			HTMLElement,			js.Function1[Event, _]]				(_.onseeked	= _)
	implicit val HTMLElement_recordNumber				= AttributeSetter[recordNumber.type,		HTMLElement,			js.Any]								(_.recordNumber	= _)
	implicit val HTMLElement_title						= AttributeSetter[titleAttr.type,			HTMLElement,			String]								(_.title	= _)
	implicit val HTMLElement_ondurationchange			= AttributeSetter[ondurationchange.type,	HTMLElement,			js.Function1[Event, _]]				(_.ondurationchange	= _)
	implicit val HTMLElement_dir						= AttributeSetter[dir.type,					HTMLElement,			String]								(_.dir	= _)
	implicit val HTMLElement_onemptied					= AttributeSetter[onemptied.type,			HTMLElement,			js.Function1[Event, _]]				(_.onemptied	= _)
	implicit val HTMLElement_onseeking					= AttributeSetter[onseeking.type,			HTMLElement,			js.Function1[Event, _]]				(_.onseeking	= _)
	implicit val HTMLElement_oncanplay					= AttributeSetter[oncanplay.type,			HTMLElement,			js.Function1[Event, _]]				(_.oncanplay	= _)
	implicit val HTMLElement_ondeactivate				= AttributeSetter[ondeactivate.type,		HTMLElement,			js.Function1[UIEvent, _]]			(_.ondeactivate	= _)
	implicit val HTMLElement_onloadstart				= AttributeSetter[onloadstart.type,			HTMLElement,			js.Function1[Event, _]]				(_.onloadstart	= _)
	implicit val HTMLElement_ondragenter				= AttributeSetter[ondragenter.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragenter	= _)
	implicit val HTMLElement_onsubmit					= AttributeSetter[onsubmit.type,			HTMLElement,			js.Function1[Event, _]]				(_.onsubmit	= _)
	implicit val HTMLElement_onchange					= AttributeSetter[onchange.type,			HTMLElement,			js.Function1[Event, _]]				(_.onchange	= _)
	implicit val HTMLElement_onbeforeactivate			= AttributeSetter[onbeforeactivate.type,	HTMLElement,			js.Function1[UIEvent, _]]			(_.onbeforeactivate	= _)
	implicit val HTMLElement_oncanplaythrough			= AttributeSetter[oncanplaythrough.type,	HTMLElement,			js.Function1[Event, _]]				(_.oncanplaythrough	= _)
	implicit val HTMLElement_onsuspend					= AttributeSetter[onsuspend.type,			HTMLElement,			js.Function1[Event, _]]				(_.onsuspend	= _)
	implicit val HTMLElement_readyState					= AttributeSetter[readyState.type,			HTMLElement,			js.Any]								(_.readyState	= _)
	implicit val HTMLElement_onmouseenter				= AttributeSetter[onmouseenter.type,		HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseenter	= _)
	implicit val HTMLElement_onmouseout					= AttributeSetter[onmouseout.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseout	= _)
	implicit val HTMLElement_parentElement				= AttributeSetter[parentElement.type,		HTMLElement,			HTMLElement]						(_.parentElement	= _)
	implicit val HTMLElement_onmousewheel				= AttributeSetter[onmousewheel.type,		HTMLElement,			js.Function1[WheelEvent, _]]		(_.onmousewheel	= _)
	implicit val HTMLElement_onvolumechange				= AttributeSetter[onvolumechange.type,		HTMLElement,			js.Function1[Event, _]]				(_.onvolumechange	= _)
	implicit val HTMLElement_filters					= AttributeSetter[filters.type,				HTMLElement,			Object]								(_.filters	= _)
	implicit val HTMLElement_ondragend					= AttributeSetter[ondragend.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragend	= _)
	implicit val HTMLElement_onbeforepaste				= AttributeSetter[onbeforepaste.type,		HTMLElement,			js.Function1[DragEvent, _]]			(_.onbeforepaste	= _)
	implicit val HTMLElement_ondragover					= AttributeSetter[ondragover.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragover	= _)
	implicit val HTMLElement_onmouseup					= AttributeSetter[onmouseup.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseup	= _)
	implicit val HTMLElement_ondragstart				= AttributeSetter[ondragstart.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragstart	= _)
	implicit val HTMLElement_onbeforecopy				= AttributeSetter[onbeforecopy.type,		HTMLElement,			js.Function1[DragEvent, _]]			(_.onbeforecopy	= _)
	implicit val HTMLElement_ondrag						= AttributeSetter[ondrag.type,				HTMLElement,			js.Function1[DragEvent, _]]			(_.ondrag	= _)
	implicit val HTMLElement_onmouseover				= AttributeSetter[onmouseover.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseover	= _)
	implicit val HTMLElement_onpause					= AttributeSetter[onpause.type,				HTMLElement,			js.Function1[Event, _]]				(_.onpause	= _)
	implicit val HTMLElement_onmousedown				= AttributeSetter[onmousedown.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmousedown	= _)
	implicit val HTMLElement_onclick					= AttributeSetter[onclick.type,				HTMLElement,			js.Function1[MouseEvent, _]]		(_.onclick	= _)
	implicit val HTMLElement_onwaiting					= AttributeSetter[onwaiting.type,			HTMLElement,			js.Function1[Event, _]]				(_.onwaiting	= _)
	implicit val HTMLElement_onstalled					= AttributeSetter[onstalled.type,			HTMLElement,			js.Function1[Event, _]]				(_.onstalled	= _)
	implicit val HTMLElement_onmousemove				= AttributeSetter[onmousemove.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmousemove	= _)
	implicit val HTMLElement_onratechange				= AttributeSetter[onratechange.type,		HTMLElement,			js.Function1[Event, _]]				(_.onratechange	= _)
	implicit val HTMLElement_contentEditable			= AttributeSetter[contentEditable.type,		HTMLElement,			String]								(_.contentEditable	= _)
	implicit val HTMLElement_tabIndex					= AttributeSetter[tabIndex.type,			HTMLElement,			Int]								(_.tabIndex	= _)
	implicit val HTMLElement_onprogress					= AttributeSetter[onprogress.type,			HTMLElement,			js.Function1[js.Any, _]]			(_.onprogress	= _)
	implicit val HTMLElement_ondblclick					= AttributeSetter[ondblclick.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.ondblclick	= _)
	implicit val HTMLElement_oncontextmenu				= AttributeSetter[oncontextmenu.type,		HTMLElement,			js.Function1[MouseEvent, _]]		(_.oncontextmenu	= _)
	implicit val HTMLElement_onloadedmetadata			= AttributeSetter[onloadedmetadata.type,	HTMLElement,			js.Function1[Event, _]]				(_.onloadedmetadata	= _)
	implicit val HTMLElement_onplay						= AttributeSetter[onplay.type,				HTMLElement,			js.Function1[Event, _]]				(_.onplay	= _)
	implicit val HTMLElement_onplaying					= AttributeSetter[onplaying.type,			HTMLElement,			js.Function1[Event, _]]				(_.onplaying	= _)
	implicit val HTMLElement_onfocusout					= AttributeSetter[onfocusout.type,			HTMLElement,			js.Function1[FocusEvent, _]]		(_.onfocusout	= _)
	implicit val HTMLElement_onabort					= AttributeSetter[onabort.type,				HTMLElement,			js.Function1[UIEvent, _]]			(_.onabort	= _)
	implicit val HTMLElement_onreadystatechange			= AttributeSetter[onreadystatechange.type,	HTMLElement,			js.Function1[Event, _]]				(_.onreadystatechange	= _)
	implicit val HTMLElement_onkeypress					= AttributeSetter[onkeypress.type,			HTMLElement,			js.Function1[KeyboardEvent, _]]		(_.onkeypress	= _)
	implicit val HTMLElement_onloadeddata				= AttributeSetter[onloadeddata.type,		HTMLElement,			js.Function1[Event, _]]				(_.onloadeddata	= _)
	implicit val HTMLElement_onbeforedeactivate			= AttributeSetter[onbeforedeactivate.type,	HTMLElement,			js.Function1[UIEvent, _]]			(_.onbeforedeactivate	= _)
	implicit val HTMLElement_onactivate					= AttributeSetter[onactivate.type,			HTMLElement,			js.Function1[UIEvent, _]]			(_.onactivate	= _)
	implicit val HTMLElement_onselectstart				= AttributeSetter[onselectstart.type,		HTMLElement,			js.Function1[Event, _]]				(_.onselectstart	= _)
	implicit val HTMLElement_ontimeupdate				= AttributeSetter[ontimeupdate.type,		HTMLElement,			js.Function1[Event, _]]				(_.ontimeupdate	= _)
	implicit val HTMLElement_onselect					= AttributeSetter[onselect.type,			HTMLElement,			js.Function1[UIEvent, _]]			(_.onselect	= _)
	implicit val HTMLElement_ondrop						= AttributeSetter[ondrop.type,				HTMLElement,			js.Function1[DragEvent, _]]			(_.ondrop	= _)
	implicit val HTMLElement_onended					= AttributeSetter[onended.type,				HTMLElement,			js.Function1[Event, _]]				(_.onended	= _)
	implicit val HTMLElement_onscroll					= AttributeSetter[onscroll.type,			HTMLElement,			js.Function1[UIEvent, _]]			(_.onscroll	= _)
	implicit val HTMLElement_oninput					= AttributeSetter[oninput.type,				HTMLElement,			js.Function1[Event, _]]				(_.oninput	= _)
	implicit val HTMLElement_oncuechange				= AttributeSetter[oncuechange.type,			HTMLElement,			js.Function1[Event, _]]				(_.oncuechange	= _)
	implicit val HTMLElement_spellcheck					= AttributeSetter[spellcheck.type,			HTMLElement,			Boolean]							(_.spellcheck	= _)
	implicit val HTMLElement_draggable					= AttributeSetter[draggable.type,			HTMLElement,			Boolean]							(_.draggable	= _)
	implicit val HTMLElement_onpointerover				= AttributeSetter[onpointerover.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerover	= _)
	implicit val HTMLElement_onpointerenter				= AttributeSetter[onpointerenter.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerenter	= _)
	implicit val HTMLElement_onpointerdown				= AttributeSetter[onpointerdown.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerdown	= _)
	implicit val HTMLElement_onpointermove				= AttributeSetter[onpointermove.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointermove	= _)
	implicit val HTMLElement_onpointerup				= AttributeSetter[onpointerup.type,			HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerup	= _)
	implicit val HTMLElement_onpointercancel			= AttributeSetter[onpointercancel.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointercancel	= _)
	implicit val HTMLElement_onpointerout				= AttributeSetter[onpointerout.type		,	HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerout	= _)
	implicit val HTMLElement_onpointerleave				= AttributeSetter[onpointerleave.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerleave	= _)
	implicit val HTMLElement_gotpointercapture			= AttributeSetter[gotpointercapture.type,	HTMLElement,			js.Function1[PointerEvent, _]]		(_.gotpointercapture	= _)
	implicit val HTMLElement_lostpointercapture			= AttributeSetter[lostpointercapture.type,	HTMLElement,			js.Function1[PointerEvent, _]]		(_.lostpointercapture	= _)

	implicit val HTMLObjectElement_width				= AttributeSetter[width.type,				HTMLObjectElement,		String]								(_.width	= _)
	// TODO check
	//implicit val HTMLObjectElement_object: Object = js.native
	implicit val HTMLObjectElement_alt					= AttributeSetter[alt.type,					HTMLObjectElement,		String]								(_.alt	= _)
	implicit val HTMLObjectElement_classid				= AttributeSetter[classid.type,				HTMLObjectElement,		String]								(_.classid	= _)
	implicit val HTMLObjectElement_name					= AttributeSetter[name.type,				HTMLObjectElement,		String]								(_.name	= _)
	implicit val HTMLObjectElement_useMap				= AttributeSetter[useMap.type,				HTMLObjectElement,		String]								(_.useMap	= _)
	implicit val HTMLObjectElement_data					= AttributeSetter[data.type,				HTMLObjectElement,		String]								(_.data	= _)
	implicit val HTMLObjectElement_height				= AttributeSetter[height.type,				HTMLObjectElement,		String]								(_.height	= _)
	implicit val HTMLObjectElement_altHtml				= AttributeSetter[altHtml.type,				HTMLObjectElement,		String]								(_.altHtml	= _)
	implicit val HTMLObjectElement_type					= AttributeSetter[`type`.type,				HTMLObjectElement,		String]								(_.`type`	= _)
	implicit val HTMLObjectElement_BaseHref				= AttributeSetter[BaseHref.type,			HTMLObjectElement,		String]								(_.BaseHref	= _)

	implicit val HTMLEmbedElement_width					= AttributeSetter[width.type,				HTMLEmbedElement,		String]								(_.width	= _)
	implicit val HTMLEmbedElement_src					= AttributeSetter[src.type,					HTMLEmbedElement,		String]								(_.src	= _)
	implicit val HTMLEmbedElement_height				= AttributeSetter[height.type,				HTMLEmbedElement,		String]								(_.height	= _)

	implicit val HTMLOptGroupElement_label				= AttributeSetter[labelAttr.type,			HTMLOptGroupElement,	String]								(_.label	= _)
	implicit val HTMLOptGroupElement_disabled			= AttributeSetter[disabled.type,			HTMLOptGroupElement,	Boolean]								(_.disabled	= _)

	implicit val HTMLVideoElement_width					= AttributeSetter[width.type,				HTMLVideoElement,		Int]								(_.width	= _)
	implicit val HTMLVideoElement_height				= AttributeSetter[height.type,				HTMLVideoElement,		Int]								(_.height	= _)
	implicit val HTMLVideoElement_poster				= AttributeSetter[poster.type,				HTMLVideoElement,		String]								(_.poster	= _)

	implicit val HTMLProgressElement_value				= AttributeSetter[value.type,				HTMLProgressElement,	Double]								(_.value	= _)
	implicit val HTMLProgressElement_max				= AttributeSetter[max.type,					HTMLProgressElement,	Double]								(_.max	= _)
	implicit val HTMLProgressElement_form				= AttributeSetter[formAttr.type,			HTMLProgressElement,	HTMLFormElement]					(_.form	= _)

	implicit val HTMLTrackElement_kind					= AttributeSetter[kind.type,				HTMLTrackElement,		String]								(_.kind	= _)
	implicit val HTMLTrackElement_src					= AttributeSetter[src.type,					HTMLTrackElement,		String]								(_.src	= _)
	implicit val HTMLTrackElement_srclang				= AttributeSetter[srclang.type,				HTMLTrackElement,		String]								(_.srclang	= _)
	implicit val HTMLTrackElement_label					= AttributeSetter[labelAttr.type,			HTMLTrackElement,		String]								(_.label	= _)

	implicit val HTMLFormElement_target					= AttributeSetter[target.type,				HTMLFormElement,		String]								(_.target	= _)
	implicit val HTMLFormElement_acceptCharset			= AttributeSetter[acceptCharset.type,		HTMLFormElement,		String]								(_.acceptCharset	= _)
	implicit val HTMLFormElement_enctype				= AttributeSetter[enctype.type,				HTMLFormElement,		String]								(_.enctype	= _)
	implicit val HTMLFormElement_action					= AttributeSetter[action.type,				HTMLFormElement,		String]								(_.action	= _)
	implicit val HTMLFormElement_name					= AttributeSetter[name.type,				HTMLFormElement,		String]								(_.name	= _)
	implicit val HTMLFormElement_method					= AttributeSetter[method.type,				HTMLFormElement,		String]								(_.method	= _)
	implicit val HTMLFormElement_encoding				= AttributeSetter[encoding.type,			HTMLFormElement,		String]								(_.encoding	= _)
	implicit val HTMLFormElement_autocomplete			= AttributeSetter[autocomplete.type,		HTMLFormElement,		String]								(_.autocomplete	= _)
	implicit val HTMLFormElement_noValidate				= AttributeSetter[noValidate.type,			HTMLFormElement,		Boolean]							(_.noValidate	= _)
}
