package sjs.diffless

import scala.scalajs.js
import org.scalajs.dom.raw._

object setters extends setters

trait setters extends attrs {
	implicit val Element_scrollTop						= AttrSetter[scrollTop.type,			Element,				Double]								(_.scrollTop	= _)
	implicit val Element_scrollLeft						= AttrSetter[scrollLeft.type,			Element,				Double]								(_.scrollLeft	= _)
	implicit val Element_outerHTML						= AttrSetter[outerHTML.type,			Element,				String]								(_.outerHTML	= _)
	implicit val Element_innerHTML						= AttrSetter[innerHTML.type,			Element,				String]								(_.innerHTML	= _)
	implicit val Element_id								= AttrSetter[id.type,					Element,				String]								(_.id	= _)
	implicit val Element_oncopy							= AttrSetter[oncopy.type,				Element,				js.Function1[ClipboardEvent, _]]	(_.oncopy	= _)
	implicit val Element_oncut							= AttrSetter[oncut.type,				Element,				js.Function1[ClipboardEvent, _]]	(_.oncut	= _)
	implicit val Element_onpaste						= AttrSetter[onpaste.type,				Element,				js.Function1[ClipboardEvent, _]]	(_.onpaste	= _)
	implicit val Element_accessKey						= AttrSetter[accessKey.type,			Element,				String]								(_.accessKey	= _)
	implicit val Element_classList						= AttrSetter[classList.type,			Element,				DOMTokenList]						(_.classList	= _)

	implicit val HTMLBaseElement_target					= AttrSetter[target.type,				HTMLBaseElement,		String]								(_.target	= _)
	implicit val HTMLBaseElement_href					= AttrSetter[href.type,					HTMLBaseElement,		String]								(_.href	= _)

	implicit val HTMLOListElement_start					= AttrSetter[start.type,				HTMLOListElement,		Int]								(_.start	= _)

	implicit val HTMLSelectElement_value				= AttrSetter[value.type,				HTMLSelectElement,		String]								(_.value	= _)
	implicit val HTMLSelectElement_name					= AttrSetter[name.type,					HTMLSelectElement,		String]								(_.name	= _)
	implicit val HTMLSelectElement_size					= AttrSetter[size.type,					HTMLSelectElement,		Int]								(_.size	= _)
	implicit val HTMLSelectElement_selectedIndex		= AttrSetter[selectedIndex.type,		HTMLSelectElement,		Int]								(_.selectedIndex	= _)
	implicit val HTMLSelectElement_multiple				= AttrSetter[multiple.type,				HTMLSelectElement,		Boolean]							(_.multiple	= _)
	implicit val HTMLSelectElement_disabled				= AttrSetter[disabled.type,				HTMLSelectElement,		Boolean]							(_.disabled	= _)
	implicit val HTMLSelectElement_autofocus			= AttrSetter[autofocus.type,			HTMLSelectElement,		Boolean]							(_.autofocus	= _)
	implicit val HTMLSelectElement_required				= AttrSetter[required.type,				HTMLSelectElement,		Boolean]							(_.required	= _)

	implicit val HTMLBlockElement_width					= AttrSetter[width.type,				HTMLBlockElement,		Double]								(_.width	= _)
	implicit val HTMLBlockElement_cite					= AttrSetter[citeAttr.type,				HTMLBlockElement,		String]								(_.cite	= _)

	implicit val HTMLMetaElement_httpEquiv				= AttrSetter[httpEquiv.type,			HTMLMetaElement,		String]								(_.httpEquiv	= _)
	implicit val HTMLMetaElement_name					= AttrSetter[name.type,					HTMLMetaElement,		String]								(_.name	= _)
	implicit val HTMLMetaElement_content				= AttrSetter[content.type,				HTMLMetaElement,		String]								(_.content	= _)
	implicit val HTMLMetaElement_url					= AttrSetter[url.type,					HTMLMetaElement,		String]								(_.url	= _)
	implicit val HTMLMetaElement_charset				= AttrSetter[charset.type,				HTMLMetaElement,		String]								(_.charset	= _)

	implicit val HTMLDDElement_noWrap					= AttrSetter[noWrap.type,				HTMLDDElement,			Boolean]							(_.noWrap	= _)

	implicit val HTMLLinkElement_rel					= AttrSetter[rel.type,					HTMLLinkElement,		String]								(_.rel	= _)
	implicit val HTMLLinkElement_target					= AttrSetter[target.type,				HTMLLinkElement,		String]								(_.target	= _)
	implicit val HTMLLinkElement_href					= AttrSetter[href.type,					HTMLLinkElement,		String]								(_.href	= _)
	implicit val HTMLLinkElement_media					= AttrSetter[media.type,				HTMLLinkElement,		String]								(_.media	= _)
	implicit val HTMLLinkElement_rev					= AttrSetter[rev.type,					HTMLLinkElement,		String]								(_.rev	= _)
	implicit val HTMLLinkElement_type					= AttrSetter[`type`.type,				HTMLLinkElement,		String]								(_.`type`	= _)
	implicit val HTMLLinkElement_hreflang				= AttrSetter[hreflang.type,				HTMLLinkElement,		String]								(_.hreflang	= _)

	implicit val HTMLOptionElement_defaultSelected		= AttrSetter[defaultSelected.type,		HTMLOptionElement,		Boolean]							(_.defaultSelected	= _)
	implicit val HTMLOptionElement_value				= AttrSetter[value.type,				HTMLOptionElement,		String]								(_.value	= _)
	implicit val HTMLOptionElement_text					= AttrSetter[textAttr.type,				HTMLOptionElement,		String]								(_.text	= _)
	implicit val HTMLOptionElement_label				= AttrSetter[labelAttr.type,			HTMLOptionElement,		String]								(_.label	= _)
	implicit val HTMLOptionElement_selected				= AttrSetter[selected.type,				HTMLOptionElement,		Boolean]							(_.selected	= _)
	implicit val HTMLOptionElement_disabled				= AttrSetter[disabled.type,				HTMLOptionElement,		Boolean]							(_.disabled	= _)

	implicit val HTMLMapElement_name					= AttrSetter[name.type,					HTMLMapElement,			String]								(_.name	= _)

	implicit val HTMLMenuElement_type					= AttrSetter[`type`.type,				HTMLMenuElement,		String]								(_.`type`	= _)

	implicit val HTMLImageElement_width					= AttrSetter[width.type,				HTMLImageElement,		Int]								(_.width	= _)
	implicit val HTMLImageElement_naturalHeight			= AttrSetter[naturalHeight.type,		HTMLImageElement,		Int]								(_.naturalHeight	= _)
	implicit val HTMLImageElement_alt					= AttrSetter[alt.type,					HTMLImageElement,		String]								(_.alt	= _)
	implicit val HTMLImageElement_src					= AttrSetter[src.type,					HTMLImageElement,		String]								(_.src	= _)
	implicit val HTMLImageElement_useMap				= AttrSetter[useMap.type,				HTMLImageElement,		String]								(_.useMap	= _)
	implicit val HTMLImageElement_naturalWidth			= AttrSetter[naturalWidth.type,			HTMLImageElement,		Int]								(_.naturalWidth	= _)
	implicit val HTMLImageElement_height				= AttrSetter[height.type,				HTMLImageElement,		Int]								(_.height	= _)
	implicit val HTMLImageElement_href					= AttrSetter[href.type,					HTMLImageElement,		String]								(_.href	= _)
	implicit val HTMLImageElement_isMap					= AttrSetter[isMap.type,				HTMLImageElement,		Boolean]							(_.isMap	= _)
	implicit val HTMLImageElement_onload				= AttrSetter[onload.type,				HTMLImageElement,		js.Function1[Event, _]]				(_.onload	= _)

	implicit val HTMLAreaElement_protocol				= AttrSetter[protocol.type,				HTMLAreaElement,		String]								(_.protocol	= _)
	implicit val HTMLAreaElement_search					= AttrSetter[search.type,				HTMLAreaElement,		String]								(_.search	= _)
	implicit val HTMLAreaElement_alt					= AttrSetter[alt.type,					HTMLAreaElement,		String]								(_.alt	= _)
	implicit val HTMLAreaElement_coords					= AttrSetter[coords.type,				HTMLAreaElement,		String]								(_.coords	= _)
	implicit val HTMLAreaElement_hostname				= AttrSetter[hostname.type,				HTMLAreaElement,		String]								(_.hostname	= _)
	implicit val HTMLAreaElement_port					= AttrSetter[port.type,					HTMLAreaElement,		String]								(_.port	= _)
	implicit val HTMLAreaElement_pathname				= AttrSetter[pathname.type,				HTMLAreaElement,		String]								(_.pathname	= _)
	implicit val HTMLAreaElement_host					= AttrSetter[host.type,					HTMLAreaElement,		String]								(_.host	= _)
	implicit val HTMLAreaElement_hash					= AttrSetter[hash.type,					HTMLAreaElement,		String]								(_.hash	= _)
	implicit val HTMLAreaElement_target					= AttrSetter[target.type,				HTMLAreaElement,		String]								(_.target	= _)
	implicit val HTMLAreaElement_href					= AttrSetter[href.type,					HTMLAreaElement,		String]								(_.href	= _)
	implicit val HTMLAreaElement_shape					= AttrSetter[shape.type,				HTMLAreaElement,		String]								(_.shape	= _)

	implicit val HTMLButtonElement_value				= AttrSetter[value.type,				HTMLButtonElement,		String]								(_.value	= _)
	implicit val HTMLButtonElement_status				= AttrSetter[status.type,				HTMLButtonElement,		js.Any]								(_.status	= _)
	implicit val HTMLButtonElement_name					= AttrSetter[name.type,					HTMLButtonElement,		String]								(_.name	= _)
	implicit val HTMLButtonElement_type					= AttrSetter[`type`.type,				HTMLButtonElement,		String]								(_.`type`	= _)
	implicit val HTMLButtonElement_disabled				= AttrSetter[disabled.type,				HTMLButtonElement,		Boolean]							(_.disabled	= _)
	implicit val HTMLButtonElement_formTarget			= AttrSetter[formTarget.type,			HTMLButtonElement,		String]								(_.formTarget	= _)
	implicit val HTMLButtonElement_formAction			= AttrSetter[formAction.type,			HTMLButtonElement,		String]								(_.formAction	= _)
	implicit val HTMLButtonElement_autofocus			= AttrSetter[autofocus.type,			HTMLButtonElement,		Boolean]							(_.autofocus	= _)
	implicit val HTMLButtonElement_formNoValidate		= AttrSetter[formNoValidate.type,		HTMLButtonElement,		String]								(_.formNoValidate	= _)
	implicit val HTMLButtonElement_formEnctype			= AttrSetter[formEnctype.type,			HTMLButtonElement,		String]								(_.formEnctype	= _)
	implicit val HTMLButtonElement_formMethod			= AttrSetter[formMethod.type,			HTMLButtonElement,		String]								(_.formMethod	= _)

	implicit val HTMLSourceElement_src					= AttrSetter[src.type,					HTMLSourceElement,		String]								(_.src	= _)
	implicit val HTMLSourceElement_media				= AttrSetter[media.type,				HTMLSourceElement,		String]								(_.media	= _)
	implicit val HTMLSourceElement_type					= AttrSetter[`type`.type,				HTMLSourceElement,		String]								(_.`type`	= _)

	implicit val HTMLScriptElement_defer				= AttrSetter[defer.type,				HTMLScriptElement,		Boolean]							(_.defer	= _)
	implicit val HTMLScriptElement_text					= AttrSetter[textAttr.type,				HTMLScriptElement,		String]								(_.text	= _)
	implicit val HTMLScriptElement_src					= AttrSetter[src.type,					HTMLScriptElement,		String]								(_.src	= _)
	implicit val HTMLScriptElement_charset				= AttrSetter[charset.type,				HTMLScriptElement,		String]								(_.charset	= _)
	implicit val HTMLScriptElement_type					= AttrSetter[`type`.type,				HTMLScriptElement,		String]								(_.`type`	= _)
	implicit val HTMLScriptElement_event				= AttrSetter[event.type,				HTMLScriptElement,		String]								(_.event	= _)
	implicit val HTMLScriptElement_async				= AttrSetter[async.type,				HTMLScriptElement,		Boolean]							(_.async	= _)
	implicit val HTMLScriptElement_onload				= AttrSetter[onload.type,				HTMLScriptElement,		js.Function1[Event, _]]				(_.onload	= _)

	implicit val HTMLTableRowElement_borderColorLight	= AttrSetter[borderColorLight.type,		HTMLTableRowElement,	js.Any]								(_.borderColorLight	= _)
	implicit val HTMLTableRowElement_borderColor		= AttrSetter[borderColor.type,			HTMLTableRowElement,	js.Any]								(_.borderColor	= _)
	implicit val HTMLTableRowElement_height				= AttrSetter[height.type,				HTMLTableRowElement,	js.Any]								(_.height	= _)
	implicit val HTMLTableRowElement_borderColorDark	= AttrSetter[borderColorDark.type,		HTMLTableRowElement,	js.Any]								(_.borderColorDark	= _)

	implicit val HTMLQuoteElement_dateTime				= AttrSetter[dateTime.type,				HTMLQuoteElement,		String]								(_.dateTime	= _)
	implicit val HTMLQuoteElement_cite					= AttrSetter[citeAttr.type,				HTMLQuoteElement,		String]								(_.cite	= _)

	implicit val HTMLLabelElement_htmlFor				= AttrSetter[htmlFor.type,				HTMLLabelElement,		String]								(_.htmlFor	= _)

	implicit val HTMLLegendElement_align				= AttrSetter[align.type,				HTMLLegendElement,		String]								(_.align	= _)

	implicit val HTMLLIElement_value					= AttrSetter[value.type,				HTMLLIElement,			Int]								(_.value	= _)

	implicit val HTMLIFrameElement_width				= AttrSetter[width.type,				HTMLIFrameElement,		String]								(_.width	= _)
	implicit val HTMLIFrameElement_src					= AttrSetter[src.type,					HTMLIFrameElement,		String]								(_.src	= _)
	implicit val HTMLIFrameElement_name					= AttrSetter[name.type,					HTMLIFrameElement,		String]								(_.name	= _)
	implicit val HTMLIFrameElement_height				= AttrSetter[height.type,				HTMLIFrameElement,		String]								(_.height	= _)
	implicit val HTMLIFrameElement_border				= AttrSetter[border.type,				HTMLIFrameElement,		String]								(_.border	= _)
	implicit val HTMLIFrameElement_security				= AttrSetter[security.type,				HTMLIFrameElement,		js.Any]								(_.security	= _)
	implicit val HTMLIFrameElement_onload				= AttrSetter[onload.type,				HTMLIFrameElement,		js.Function1[Event, _]]				(_.onload	= _)
	implicit val HTMLIFrameElement_sandbox				= AttrSetter[sandbox.type,				HTMLIFrameElement,		DOMSettableTokenList]				(_.sandbox	= _)

	implicit val HTMLBodyElement_scroll					= AttrSetter[scroll.type,				HTMLBodyElement,		String]								(_.scroll	= _)
	implicit val HTMLBodyElement_ononline				= AttrSetter[ononline.type,				HTMLBodyElement,		js.Function1[Event, _]]				(_.ononline	= _)
	implicit val HTMLBodyElement_onmessage				= AttrSetter[onmessage.type,			HTMLBodyElement,		js.Function1[MessageEvent, _]]		(_.onmessage	= _)
	implicit val HTMLBodyElement_onerror				= AttrSetter[onerror.type,				HTMLBodyElement,		js.Function1[Event, _]]				(_.onerror	= _)
	implicit val HTMLBodyElement_onresize				= AttrSetter[onresize.type,				HTMLBodyElement,		js.Function1[UIEvent, _]]			(_.onresize	= _)
	implicit val HTMLBodyElement_onafterprint			= AttrSetter[onafterprint.type,			HTMLBodyElement,		js.Function1[Event, _]]				(_.onafterprint	= _)
	implicit val HTMLBodyElement_onbeforeprint			= AttrSetter[onbeforeprint.type,		HTMLBodyElement,		js.Function1[Event, _]]				(_.onbeforeprint	= _)
	implicit val HTMLBodyElement_onoffline				= AttrSetter[onoffline.type,			HTMLBodyElement,		js.Function1[Event, _]]				(_.onoffline	= _)
	implicit val HTMLBodyElement_onunload				= AttrSetter[onunload.type,				HTMLBodyElement,		js.Function1[Event, _]]				(_.onunload	= _)
	implicit val HTMLBodyElement_onhashchange			= AttrSetter[onhashchange.type,			HTMLBodyElement,		js.Function1[Event, _]]				(_.onhashchange	= _)
	implicit val HTMLBodyElement_onload					= AttrSetter[onload.type,				HTMLBodyElement,		js.Function1[Event, _]]				(_.onload	= _)
	implicit val HTMLBodyElement_onbeforeunload			= AttrSetter[onbeforeunload.type,		HTMLBodyElement,		js.Function1[BeforeUnloadEvent, _]]	(_.onbeforeunload	= _)
	implicit val HTMLBodyElement_onstorage				= AttrSetter[onstorage.type,			HTMLBodyElement,		js.Function1[StorageEvent, _]]		(_.onstorage	= _)
	implicit val HTMLBodyElement_onpopstate				= AttrSetter[onpopstate.type,			HTMLBodyElement,		js.Function1[PopStateEvent, _]]		(_.onpopstate	= _)

	implicit val HTMLInputElement_width					= AttrSetter[width.type,				HTMLInputElement,		String]								(_.width	= _)
	implicit val HTMLInputElement_status				= AttrSetter[status.type,				HTMLInputElement,		Boolean]							(_.status	= _)
	implicit val HTMLInputElement_selectionStart		= AttrSetter[selectionStart.type,		HTMLInputElement,		Int]								(_.selectionStart	= _)
	implicit val HTMLInputElement_indeterminate			= AttrSetter[indeterminate.type,		HTMLInputElement,		Boolean]							(_.indeterminate	= _)
	implicit val HTMLInputElement_readOnly				= AttrSetter[readOnly.type,				HTMLInputElement,		Boolean]							(_.readOnly	= _)
	implicit val HTMLInputElement_size					= AttrSetter[size.type,					HTMLInputElement,		Int]								(_.size	= _)
	implicit val HTMLInputElement_selectionEnd			= AttrSetter[selectionEnd.type,			HTMLInputElement,		Int]								(_.selectionEnd	= _)
	implicit val HTMLInputElement_accept				= AttrSetter[accept.type,				HTMLInputElement,		String]								(_.accept	= _)
	implicit val HTMLInputElement_alt					= AttrSetter[alt.type,					HTMLInputElement,		String]								(_.alt	= _)
	implicit val HTMLInputElement_defaultChecked		= AttrSetter[defaultChecked.type,		HTMLInputElement,		Boolean]							(_.defaultChecked	= _)
	implicit val HTMLInputElement_value					= AttrSetter[value.type,				HTMLInputElement,		String]								(_.value	= _)
	implicit val HTMLInputElement_src					= AttrSetter[src.type,					HTMLInputElement,		String]								(_.src	= _)
	implicit val HTMLInputElement_name					= AttrSetter[name.type,					HTMLInputElement,		String]								(_.name	= _)
	implicit val HTMLInputElement_height				= AttrSetter[height.type,				HTMLInputElement,		String]								(_.height	= _)
	implicit val HTMLInputElement_checked				= AttrSetter[checked.type,				HTMLInputElement,		Boolean]							(_.checked	= _)
	implicit val HTMLInputElement_disabled				= AttrSetter[disabled.type,				HTMLInputElement,		Boolean]							(_.disabled	= _)
	implicit val HTMLInputElement_maxLength				= AttrSetter[maxLength.type,			HTMLInputElement,		Int]								(_.maxLength	= _)
	implicit val HTMLInputElement_type					= AttrSetter[`type`.type,				HTMLInputElement,		String]								(_.`type`	= _)
	implicit val HTMLInputElement_defaultValue			= AttrSetter[defaultValue.type,			HTMLInputElement,		String]								(_.defaultValue	= _)
	implicit val HTMLInputElement_files					= AttrSetter[files.type,				HTMLInputElement,		FileList]							(_.files	= _)
	implicit val HTMLInputElement_max					= AttrSetter[max.type,					HTMLInputElement,		String]								(_.max	= _)
	implicit val HTMLInputElement_formTarget			= AttrSetter[formTarget.type,			HTMLInputElement,		String]								(_.formTarget	= _)
	implicit val HTMLInputElement_step					= AttrSetter[step.type,					HTMLInputElement,		String]								(_.step	= _)
	implicit val HTMLInputElement_autofocus				= AttrSetter[autofocus.type,			HTMLInputElement,		Boolean]							(_.autofocus	= _)
	implicit val HTMLInputElement_required				= AttrSetter[required.type,				HTMLInputElement,		Boolean]							(_.required	= _)
	implicit val HTMLInputElement_formEnctype			= AttrSetter[formEnctype.type,			HTMLInputElement,		String]								(_.formEnctype	= _)
	implicit val HTMLInputElement_valueAsNumber			= AttrSetter[valueAsNumber.type,		HTMLInputElement,		Double]								(_.valueAsNumber	= _)
	implicit val HTMLInputElement_placeholder			= AttrSetter[placeholder.type,			HTMLInputElement,		String]								(_.placeholder	= _)
	implicit val HTMLInputElement_formMethod			= AttrSetter[formMethod.type,			HTMLInputElement,		String]								(_.formMethod	= _)
	implicit val HTMLInputElement_list					= AttrSetter[list.type,					HTMLInputElement,		HTMLElement]						(_.list	= _)
	implicit val HTMLInputElement_autocomplete			= AttrSetter[autocomplete.type,			HTMLInputElement,		String]								(_.autocomplete	= _)
	implicit val HTMLInputElement_min					= AttrSetter[min.type,					HTMLInputElement,		String]								(_.min	= _)
	implicit val HTMLInputElement_formAction			= AttrSetter[formAction.type,			HTMLInputElement,		String]								(_.formAction	= _)
	implicit val HTMLInputElement_pattern				= AttrSetter[pattern.type,				HTMLInputElement,		String]								(_.pattern	= _)
	implicit val HTMLInputElement_formNoValidate		= AttrSetter[formNoValidate.type,		HTMLInputElement,		String]								(_.formNoValidate	= _)
	implicit val HTMLInputElement_multiple				= AttrSetter[multiple.type,				HTMLInputElement,		Boolean]							(_.multiple	= _)

	implicit val HTMLAnchorElement_rel					= AttrSetter[rel.type,					HTMLAnchorElement,		String]								(_.rel	= _)
	implicit val HTMLAnchorElement_protocol				= AttrSetter[protocol.type,				HTMLAnchorElement,		String]								(_.protocol	= _)
	implicit val HTMLAnchorElement_search				= AttrSetter[search.type,				HTMLAnchorElement,		String]								(_.search	= _)
	implicit val HTMLAnchorElement_hostname				= AttrSetter[hostname.type,				HTMLAnchorElement,		String]								(_.hostname	= _)
	implicit val HTMLAnchorElement_pathname				= AttrSetter[pathname.type,				HTMLAnchorElement,		String]								(_.pathname	= _)
	implicit val HTMLAnchorElement_target				= AttrSetter[target.type,				HTMLAnchorElement,		String]								(_.target	= _)
	implicit val HTMLAnchorElement_href					= AttrSetter[href.type,					HTMLAnchorElement,		String]								(_.href	= _)
	implicit val HTMLAnchorElement_charset				= AttrSetter[charset.type,				HTMLAnchorElement,		String]								(_.charset	= _)
	implicit val HTMLAnchorElement_hreflang				= AttrSetter[hreflang.type,				HTMLAnchorElement,		String]								(_.hreflang	= _)
	implicit val HTMLAnchorElement_port					= AttrSetter[port.type,					HTMLAnchorElement,		String]								(_.port	= _)
	implicit val HTMLAnchorElement_host					= AttrSetter[host.type,					HTMLAnchorElement,		String]								(_.host	= _)
	implicit val HTMLAnchorElement_hash					= AttrSetter[hash.type,					HTMLAnchorElement,		String]								(_.hash	= _)
	implicit val HTMLAnchorElement_type					= AttrSetter[`type`.type,				HTMLAnchorElement,		String]								(_.`type`	= _)
	implicit val HTMLAnchorElement_mimeType				= AttrSetter[mimeType.type,				HTMLAnchorElement,		String]								(_.mimeType	= _)
	implicit val HTMLAnchorElement_text					= AttrSetter[textAttr.type,				HTMLAnchorElement,		String]								(_.text	= _)
	// TODO hack: as download is experimental, it's not in the API as a property yet
	implicit val HTMLAnchorElement_download				= AttrSetter[download.type,				HTMLAnchorElement,		String]								(_ setAttribute ("download", _))


	implicit val HTMLParamElement_value					= AttrSetter[value.type,				HTMLParamElement,		String]								(_.value	= _)
	implicit val HTMLParamElement_name					= AttrSetter[name.type,					HTMLParamElement,		String]								(_.name	= _)

	implicit val HTMLPhraseElement_dateTime				= AttrSetter[dateTime.type,				HTMLPhraseElement,		String]								(_.dateTime	= _)

	implicit val HTMLCanvasElement_width				= AttrSetter[width.type,				HTMLCanvasElement,		Int]								(_.width	= _)
	implicit val HTMLCanvasElement_height				= AttrSetter[height.type,				HTMLCanvasElement,		Int]								(_.height	= _)

	implicit val HTMLTitleElement_text					= AttrSetter[textAttr.type,				HTMLTitleElement,		String]								(_.text	= _)

	implicit val HTMLStyleElement_media					= AttrSetter[media.type,				HTMLStyleElement,		String]								(_.media	= _)
	implicit val HTMLStyleElement_type					= AttrSetter[`type`.type,				HTMLStyleElement,		String]								(_.`type`	= _)

	implicit val HTMLTableCellElement_colSpan			= AttrSetter[colSpan.type,				HTMLTableCellElement,	Int]								(_.colSpan	= _)
	implicit val HTMLTableCellElement_rowSpan			= AttrSetter[rowSpan.type,				HTMLTableCellElement,	Int]								(_.rowSpan	= _)

	implicit val HTMLTextAreaElement_value				= AttrSetter[value.type,				HTMLTextAreaElement,	String]								(_.value	= _)
	implicit val HTMLTextAreaElement_status				= AttrSetter[status.type,				HTMLTextAreaElement,	js.Any]								(_.status	= _)
	implicit val HTMLTextAreaElement_name				= AttrSetter[name.type,					HTMLTextAreaElement,	String]								(_.name	= _)
	implicit val HTMLTextAreaElement_disabled			= AttrSetter[disabled.type,				HTMLTextAreaElement,	Boolean]							(_.disabled	= _)
	implicit val HTMLTextAreaElement_selectionStart		= AttrSetter[selectionStart.type,		HTMLTextAreaElement,	Int]								(_.selectionStart	= _)
	implicit val HTMLTextAreaElement_rows				= AttrSetter[rows.type,					HTMLTextAreaElement,	Int]								(_.rows	= _)
	implicit val HTMLTextAreaElement_cols				= AttrSetter[cols.type,					HTMLTextAreaElement,	Int]								(_.cols	= _)
	implicit val HTMLTextAreaElement_readOnly			= AttrSetter[readOnly.type,				HTMLTextAreaElement,	Boolean]							(_.readOnly	= _)
	implicit val HTMLTextAreaElement_wrap				= AttrSetter[wrap.type,					HTMLTextAreaElement,	String]								(_.wrap	= _)
	implicit val HTMLTextAreaElement_selectionEnd		= AttrSetter[selectionEnd.type,			HTMLTextAreaElement,	Int]								(_.selectionEnd	= _)
	implicit val HTMLTextAreaElement_defaultValue		= AttrSetter[defaultValue.type,			HTMLTextAreaElement,	String]								(_.defaultValue	= _)
	implicit val HTMLTextAreaElement_autofocus			= AttrSetter[autofocus.type,			HTMLTextAreaElement,	Boolean]							(_.autofocus	= _)
	implicit val HTMLTextAreaElement_required			= AttrSetter[required.type,				HTMLTextAreaElement,	Boolean]							(_.required	= _)
	implicit val HTMLTextAreaElement_maxLength			= AttrSetter[maxLength.type,			HTMLTextAreaElement,	Int]								(_.maxLength	= _)
	implicit val HTMLTextAreaElement_placeholder		= AttrSetter[placeholder.type,			HTMLTextAreaElement,	String]								(_.placeholder	= _)

	implicit val HTMLModElement_dateTime				= AttrSetter[dateTime.type,				HTMLModElement,			String]								(_.dateTime	= _)
	implicit val HTMLModElement_cite					= AttrSetter[citeAttr.type,				HTMLModElement,			String]								(_.cite	= _)

	implicit val HTMLTableColElement_span				= AttrSetter[spanAttr.type,				HTMLTableColElement,	Int]								(_.span	= _)

	implicit val HTMLMediaElement_loop					= AttrSetter[loop.type,					HTMLMediaElement,		Boolean]							(_.loop	= _)
	implicit val HTMLMediaElement_autoplay				= AttrSetter[autoplay.type,				HTMLMediaElement,		Boolean]							(_.autoplay	= _)
	implicit val HTMLMediaElement_controls				= AttrSetter[controls.type,				HTMLMediaElement,		Boolean]							(_.controls	= _)
	implicit val HTMLMediaElement_volume				= AttrSetter[volume.type,				HTMLMediaElement,		Double]								(_.volume	= _)
	implicit val HTMLMediaElement_src					= AttrSetter[src.type,					HTMLMediaElement,		String]								(_.src	= _)
	implicit val HTMLMediaElement_playbackRate			= AttrSetter[playbackRate.type,			HTMLMediaElement,		Double]								(_.playbackRate	= _)
	implicit val HTMLMediaElement_muted					= AttrSetter[muted.type,				HTMLMediaElement,		Boolean]							(_.muted	= _)
	implicit val HTMLMediaElement_defaultPlaybackRate	= AttrSetter[defaultPlaybackRate.type,	HTMLMediaElement,		Double]								(_.defaultPlaybackRate	= _)
	implicit val HTMLMediaElement_currentTime			= AttrSetter[currentTime.type,			HTMLMediaElement,		Double]								(_.currentTime	= _)
	implicit val HTMLMediaElement_preload				= AttrSetter[preload.type,				HTMLMediaElement,		String]								(_.preload	= _)

	implicit val HTMLDTElement_noWrap					= AttrSetter[noWrap.type,				HTMLDTElement,			Boolean]							(_.noWrap	= _)

	implicit val HTMLFieldSetElement_disabled			= AttrSetter[disabled.type,				HTMLFieldSetElement,	Boolean]							(_.disabled	= _)

	implicit val HTMLElement_onblur						= AttrSetter[onblur.type,				HTMLElement,			js.Function1[FocusEvent, _]]		(_.onblur	= _)
	implicit val HTMLElement_onfocus					= AttrSetter[onfocus.type,				HTMLElement,			js.Function1[FocusEvent, _]]		(_.onfocus	= _)
	implicit val HTMLElement_onmouseleave				= AttrSetter[onmouseleave.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseleave	= _)
	implicit val HTMLElement_onbeforecut				= AttrSetter[onbeforecut.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.onbeforecut	= _)
	implicit val HTMLElement_onkeydown					= AttrSetter[onkeydown.type,			HTMLElement,			js.Function1[KeyboardEvent, _]]		(_.onkeydown	= _)
	implicit val HTMLElement_onkeyup					= AttrSetter[onkeyup.type,				HTMLElement,			js.Function1[KeyboardEvent, _]]		(_.onkeyup	= _)
	implicit val HTMLElement_onreset					= AttrSetter[onreset.type,				HTMLElement,			js.Function1[Event, _]]				(_.onreset	= _)
	implicit val HTMLElement_onhelp						= AttrSetter[onhelp.type,				HTMLElement,			js.Function1[Event, _]]				(_.onhelp	= _)
	implicit val HTMLElement_ondragleave				= AttrSetter[ondragleave.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragleave	= _)
	implicit val HTMLElement_className					= AttrSetter[className.type,			HTMLElement,			String]								(_.className	= _)
	implicit val HTMLElement_onfocusin					= AttrSetter[onfocusin.type,			HTMLElement,			js.Function1[FocusEvent, _]]		(_.onfocusin	= _)
	implicit val HTMLElement_onseeked					= AttrSetter[onseeked.type,				HTMLElement,			js.Function1[Event, _]]				(_.onseeked	= _)
	implicit val HTMLElement_recordNumber				= AttrSetter[recordNumber.type,			HTMLElement,			js.Any]								(_.recordNumber	= _)
	implicit val HTMLElement_title						= AttrSetter[titleAttr.type,			HTMLElement,			String]								(_.title	= _)
	implicit val HTMLElement_ondurationchange			= AttrSetter[ondurationchange.type,		HTMLElement,			js.Function1[Event, _]]				(_.ondurationchange	= _)
	implicit val HTMLElement_dir						= AttrSetter[dir.type,					HTMLElement,			String]								(_.dir	= _)
	implicit val HTMLElement_onemptied					= AttrSetter[onemptied.type,			HTMLElement,			js.Function1[Event, _]]				(_.onemptied	= _)
	implicit val HTMLElement_onseeking					= AttrSetter[onseeking.type,			HTMLElement,			js.Function1[Event, _]]				(_.onseeking	= _)
	implicit val HTMLElement_oncanplay					= AttrSetter[oncanplay.type,			HTMLElement,			js.Function1[Event, _]]				(_.oncanplay	= _)
	implicit val HTMLElement_ondeactivate				= AttrSetter[ondeactivate.type,			HTMLElement,			js.Function1[UIEvent, _]]			(_.ondeactivate	= _)
	implicit val HTMLElement_onloadstart				= AttrSetter[onloadstart.type,			HTMLElement,			js.Function1[Event, _]]				(_.onloadstart	= _)
	implicit val HTMLElement_ondragenter				= AttrSetter[ondragenter.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragenter	= _)
	implicit val HTMLElement_onsubmit					= AttrSetter[onsubmit.type,				HTMLElement,			js.Function1[Event, _]]				(_.onsubmit	= _)
	implicit val HTMLElement_onchange					= AttrSetter[onchange.type,				HTMLElement,			js.Function1[Event, _]]				(_.onchange	= _)
	implicit val HTMLElement_onbeforeactivate			= AttrSetter[onbeforeactivate.type,		HTMLElement,			js.Function1[UIEvent, _]]			(_.onbeforeactivate	= _)
	implicit val HTMLElement_oncanplaythrough			= AttrSetter[oncanplaythrough.type,		HTMLElement,			js.Function1[Event, _]]				(_.oncanplaythrough	= _)
	implicit val HTMLElement_onsuspend					= AttrSetter[onsuspend.type,			HTMLElement,			js.Function1[Event, _]]				(_.onsuspend	= _)
	implicit val HTMLElement_readyState					= AttrSetter[readyState.type,			HTMLElement,			js.Any]								(_.readyState	= _)
	implicit val HTMLElement_onmouseenter				= AttrSetter[onmouseenter.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseenter	= _)
	implicit val HTMLElement_onmouseout					= AttrSetter[onmouseout.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseout	= _)
	implicit val HTMLElement_parentElement				= AttrSetter[parentElement.type,		HTMLElement,			HTMLElement]						(_.parentElement	= _)
	implicit val HTMLElement_onmousewheel				= AttrSetter[onmousewheel.type,			HTMLElement,			js.Function1[WheelEvent, _]]		(_.onmousewheel	= _)
	implicit val HTMLElement_onvolumechange				= AttrSetter[onvolumechange.type,		HTMLElement,			js.Function1[Event, _]]				(_.onvolumechange	= _)
	implicit val HTMLElement_filters					= AttrSetter[filters.type,				HTMLElement,			Object]								(_.filters	= _)
	implicit val HTMLElement_ondragend					= AttrSetter[ondragend.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragend	= _)
	implicit val HTMLElement_onbeforepaste				= AttrSetter[onbeforepaste.type,		HTMLElement,			js.Function1[DragEvent, _]]			(_.onbeforepaste	= _)
	implicit val HTMLElement_ondragover					= AttrSetter[ondragover.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragover	= _)
	implicit val HTMLElement_onmouseup					= AttrSetter[onmouseup.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseup	= _)
	implicit val HTMLElement_ondragstart				= AttrSetter[ondragstart.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.ondragstart	= _)
	implicit val HTMLElement_onbeforecopy				= AttrSetter[onbeforecopy.type,			HTMLElement,			js.Function1[DragEvent, _]]			(_.onbeforecopy	= _)
	implicit val HTMLElement_ondrag						= AttrSetter[ondrag.type,				HTMLElement,			js.Function1[DragEvent, _]]			(_.ondrag	= _)
	implicit val HTMLElement_onmouseover				= AttrSetter[onmouseover.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmouseover	= _)
	implicit val HTMLElement_onpause					= AttrSetter[onpause.type,				HTMLElement,			js.Function1[Event, _]]				(_.onpause	= _)
	implicit val HTMLElement_onmousedown				= AttrSetter[onmousedown.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmousedown	= _)
	implicit val HTMLElement_onclick					= AttrSetter[onclick.type,				HTMLElement,			js.Function1[MouseEvent, _]]		(_.onclick	= _)
	implicit val HTMLElement_onwaiting					= AttrSetter[onwaiting.type,			HTMLElement,			js.Function1[Event, _]]				(_.onwaiting	= _)
	implicit val HTMLElement_onstalled					= AttrSetter[onstalled.type,			HTMLElement,			js.Function1[Event, _]]				(_.onstalled	= _)
	implicit val HTMLElement_onmousemove				= AttrSetter[onmousemove.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.onmousemove	= _)
	implicit val HTMLElement_onratechange				= AttrSetter[onratechange.type,			HTMLElement,			js.Function1[Event, _]]				(_.onratechange	= _)
	implicit val HTMLElement_contentEditable			= AttrSetter[contentEditable.type,		HTMLElement,			String]								(_.contentEditable	= _)
	implicit val HTMLElement_tabIndex					= AttrSetter[tabIndex.type,				HTMLElement,			Int]								(_.tabIndex	= _)
	implicit val HTMLElement_onprogress					= AttrSetter[onprogress.type,			HTMLElement,			js.Function1[js.Any, _]]			(_.onprogress	= _)
	implicit val HTMLElement_ondblclick					= AttrSetter[ondblclick.type,			HTMLElement,			js.Function1[MouseEvent, _]]		(_.ondblclick	= _)
	implicit val HTMLElement_oncontextmenu				= AttrSetter[oncontextmenu.type,		HTMLElement,			js.Function1[MouseEvent, _]]		(_.oncontextmenu	= _)
	implicit val HTMLElement_onloadedmetadata			= AttrSetter[onloadedmetadata.type,		HTMLElement,			js.Function1[Event, _]]				(_.onloadedmetadata	= _)
	implicit val HTMLElement_onplay						= AttrSetter[onplay.type,				HTMLElement,			js.Function1[Event, _]]				(_.onplay	= _)
	implicit val HTMLElement_onplaying					= AttrSetter[onplaying.type,			HTMLElement,			js.Function1[Event, _]]				(_.onplaying	= _)
	implicit val HTMLElement_onfocusout					= AttrSetter[onfocusout.type,			HTMLElement,			js.Function1[FocusEvent, _]]		(_.onfocusout	= _)
	implicit val HTMLElement_onabort					= AttrSetter[onabort.type,				HTMLElement,			js.Function1[UIEvent, _]]			(_.onabort	= _)
	implicit val HTMLElement_onreadystatechange			= AttrSetter[onreadystatechange.type,	HTMLElement,			js.Function1[Event, _]]				(_.onreadystatechange	= _)
	implicit val HTMLElement_onkeypress					= AttrSetter[onkeypress.type,			HTMLElement,			js.Function1[KeyboardEvent, _]]		(_.onkeypress	= _)
	implicit val HTMLElement_onloadeddata				= AttrSetter[onloadeddata.type,			HTMLElement,			js.Function1[Event, _]]				(_.onloadeddata	= _)
	implicit val HTMLElement_onbeforedeactivate			= AttrSetter[onbeforedeactivate.type,	HTMLElement,			js.Function1[UIEvent, _]]			(_.onbeforedeactivate	= _)
	implicit val HTMLElement_onactivate					= AttrSetter[onactivate.type,			HTMLElement,			js.Function1[UIEvent, _]]			(_.onactivate	= _)
	implicit val HTMLElement_onselectstart				= AttrSetter[onselectstart.type,		HTMLElement,			js.Function1[Event, _]]				(_.onselectstart	= _)
	implicit val HTMLElement_ontimeupdate				= AttrSetter[ontimeupdate.type,			HTMLElement,			js.Function1[Event, _]]				(_.ontimeupdate	= _)
	implicit val HTMLElement_onselect					= AttrSetter[onselect.type,				HTMLElement,			js.Function1[UIEvent, _]]			(_.onselect	= _)
	implicit val HTMLElement_ondrop						= AttrSetter[ondrop.type,				HTMLElement,			js.Function1[DragEvent, _]]			(_.ondrop	= _)
	implicit val HTMLElement_onended					= AttrSetter[onended.type,				HTMLElement,			js.Function1[Event, _]]				(_.onended	= _)
	implicit val HTMLElement_onscroll					= AttrSetter[onscroll.type,				HTMLElement,			js.Function1[UIEvent, _]]			(_.onscroll	= _)
	implicit val HTMLElement_oninput					= AttrSetter[oninput.type,				HTMLElement,			js.Function1[Event, _]]				(_.oninput	= _)
	implicit val HTMLElement_oncuechange				= AttrSetter[oncuechange.type,			HTMLElement,			js.Function1[Event, _]]				(_.oncuechange	= _)
	implicit val HTMLElement_spellcheck					= AttrSetter[spellcheck.type,			HTMLElement,			Boolean]							(_.spellcheck	= _)
	implicit val HTMLElement_draggable					= AttrSetter[draggable.type,			HTMLElement,			Boolean]							(_.draggable	= _)
	implicit val HTMLElement_onpointerover				= AttrSetter[onpointerover.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerover	= _)
	implicit val HTMLElement_onpointerenter				= AttrSetter[onpointerenter.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerenter	= _)
	implicit val HTMLElement_onpointerdown				= AttrSetter[onpointerdown.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerdown	= _)
	implicit val HTMLElement_onpointermove				= AttrSetter[onpointermove.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointermove	= _)
	implicit val HTMLElement_onpointerup				= AttrSetter[onpointerup.type,			HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerup	= _)
	implicit val HTMLElement_onpointercancel			= AttrSetter[onpointercancel.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointercancel	= _)
	implicit val HTMLElement_onpointerout				= AttrSetter[onpointerout.type		,	HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerout	= _)
	implicit val HTMLElement_onpointerleave				= AttrSetter[onpointerleave.type,		HTMLElement,			js.Function1[PointerEvent, _]]		(_.onpointerleave	= _)
	implicit val HTMLElement_gotpointercapture			= AttrSetter[gotpointercapture.type,	HTMLElement,			js.Function1[PointerEvent, _]]		(_.gotpointercapture	= _)
	implicit val HTMLElement_lostpointercapture			= AttrSetter[lostpointercapture.type,	HTMLElement,			js.Function1[PointerEvent, _]]		(_.lostpointercapture	= _)

	implicit val HTMLObjectElement_width				= AttrSetter[width.type,				HTMLObjectElement,		String]								(_.width	= _)
	// TODO check
	//implicit val HTMLObjectElement_object: Object = js.native
	implicit val HTMLObjectElement_alt					= AttrSetter[alt.type,					HTMLObjectElement,		String]								(_.alt	= _)
	implicit val HTMLObjectElement_classid				= AttrSetter[classid.type,				HTMLObjectElement,		String]								(_.classid	= _)
	implicit val HTMLObjectElement_name					= AttrSetter[name.type,					HTMLObjectElement,		String]								(_.name	= _)
	implicit val HTMLObjectElement_useMap				= AttrSetter[useMap.type,				HTMLObjectElement,		String]								(_.useMap	= _)
	implicit val HTMLObjectElement_data					= AttrSetter[data.type,					HTMLObjectElement,		String]								(_.data	= _)
	implicit val HTMLObjectElement_height				= AttrSetter[height.type,				HTMLObjectElement,		String]								(_.height	= _)
	implicit val HTMLObjectElement_altHtml				= AttrSetter[altHtml.type,				HTMLObjectElement,		String]								(_.altHtml	= _)
	implicit val HTMLObjectElement_type					= AttrSetter[`type`.type,				HTMLObjectElement,		String]								(_.`type`	= _)
	implicit val HTMLObjectElement_BaseHref				= AttrSetter[BaseHref.type,				HTMLObjectElement,		String]								(_.BaseHref	= _)

	implicit val HTMLEmbedElement_width					= AttrSetter[width.type,				HTMLEmbedElement,		String]								(_.width	= _)
	implicit val HTMLEmbedElement_src					= AttrSetter[src.type,					HTMLEmbedElement,		String]								(_.src	= _)
	implicit val HTMLEmbedElement_height				= AttrSetter[height.type,				HTMLEmbedElement,		String]								(_.height	= _)

	implicit val HTMLOptGroupElement_label				= AttrSetter[labelAttr.type,			HTMLOptGroupElement,	String]								(_.label	= _)
	implicit val HTMLOptGroupElement_disabled			= AttrSetter[disabled.type,				HTMLOptGroupElement,	Boolean]								(_.disabled	= _)

	implicit val HTMLVideoElement_width					= AttrSetter[width.type,				HTMLVideoElement,		Int]								(_.width	= _)
	implicit val HTMLVideoElement_height				= AttrSetter[height.type,				HTMLVideoElement,		Int]								(_.height	= _)
	implicit val HTMLVideoElement_poster				= AttrSetter[poster.type,				HTMLVideoElement,		String]								(_.poster	= _)

	implicit val HTMLProgressElement_value				= AttrSetter[value.type,				HTMLProgressElement,	Double]								(_.value	= _)
	implicit val HTMLProgressElement_max				= AttrSetter[max.type,					HTMLProgressElement,	Double]								(_.max	= _)
	implicit val HTMLProgressElement_form				= AttrSetter[formAttr.type,				HTMLProgressElement,	HTMLFormElement]					(_.form	= _)

	implicit val HTMLTrackElement_kind					= AttrSetter[kind.type,					HTMLTrackElement,		String]								(_.kind	= _)
	implicit val HTMLTrackElement_src					= AttrSetter[src.type,					HTMLTrackElement,		String]								(_.src	= _)
	implicit val HTMLTrackElement_srclang				= AttrSetter[srclang.type,				HTMLTrackElement,		String]								(_.srclang	= _)
	implicit val HTMLTrackElement_label					= AttrSetter[labelAttr.type,			HTMLTrackElement,		String]								(_.label	= _)

	implicit val HTMLFormElement_target					= AttrSetter[target.type,				HTMLFormElement,		String]								(_.target	= _)
	implicit val HTMLFormElement_acceptCharset			= AttrSetter[acceptCharset.type,		HTMLFormElement,		String]								(_.acceptCharset	= _)
	implicit val HTMLFormElement_enctype				= AttrSetter[enctype.type,				HTMLFormElement,		String]								(_.enctype	= _)
	implicit val HTMLFormElement_action					= AttrSetter[action.type,				HTMLFormElement,		String]								(_.action	= _)
	implicit val HTMLFormElement_name					= AttrSetter[name.type,					HTMLFormElement,		String]								(_.name	= _)
	implicit val HTMLFormElement_method					= AttrSetter[method.type,				HTMLFormElement,		String]								(_.method	= _)
	implicit val HTMLFormElement_encoding				= AttrSetter[encoding.type,				HTMLFormElement,		String]								(_.encoding	= _)
	implicit val HTMLFormElement_autocomplete			= AttrSetter[autocomplete.type,			HTMLFormElement,		String]								(_.autocomplete	= _)
	implicit val HTMLFormElement_noValidate				= AttrSetter[noValidate.type,			HTMLFormElement,		Boolean]							(_.noValidate	= _)
}
